---
- hosts: all

  tasks:
  - name: Start Spring Pet Clinic Mvnw
    command: ./mvnw package
    args:
      chdir: /var/www/springpetclinc/
  
  
  tasks:
  - name: Start Spring Pet Clinic Mvnw
    shell: "nohup java  -jar /var/www/springpetclinc.jar &"
