---
- hosts: all

  tasks:
  - name: Start Spring Pet Clinic Mvnw
    command: ./mvnw package
    args:
      chdir: /var/www/springpetclinc/
  
  tasks:
  - name: Start Spring Pet Clinic Mvnw
    shell: java -jar spring-petclinic-2.3.1.jar 
    args:
      chdir: /var/www/springpetclinc/target
